# typed: true
# frozen_string_literal: true
#
# Homebrew Formula for SupCode
# Auto-generated by GoReleaser — version placeholder will be replaced
# during release pipeline.
#
# Install: brew install supcode/tap/supcode

class Supcode < Formula
  desc "SupCode - AI coding agent with multi-agent collaboration"
  homepage "https://github.com/supcode/supcode"
  license "MIT"
  version "{{ .Version }}"

  on_macos do
    if Hardware::CPU.physical_cpu_arm?
      url "https://github.com/supcode/supcode/releases/download/v#{version}/supcode_#{version}_macOS_arm64.tar.gz"
      sha256 "{{ .ArtifactSHA256 }}"
    elsif Hardware::CPU.intel?
      url "https://github.com/supcode/supcode/releases/download/v#{version}/supcode_#{version}_macOS_x86_64.tar.gz"
      sha256 "{{ .ArtifactSHA256 }}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/supcode/supcode/releases/download/v#{version}/supcode_#{version}_linux_arm64.tar.gz"
      sha256 "{{ .ArtifactSHA256 }}"
    elsif Hardware::CPU.intel?
      url "https://github.com/supcode/supcode/releases/download/v#{version}/supcode_#{version}_linux_x86_64.tar.gz"
      sha256 "{{ .ArtifactSHA256 }}"
    end
  end

  def install
    bin.install "supcode"
  end

  test do
    system "#{bin}/supcode", "--help"
  end
end
